config/routes.rb
ProjectManager::Application.routes.draw do

  devise_for :users
  resources :projects
  resources :tasks
  root to: 'pages#home'

  

end

app/models/project.rb
class Project < ActiveRecord::Base

  # simpler version:
  has_many :project_users
  has_many :users, through: :project_users
  has_many :tasks


  # # complicated version: 

  ROLE = {
    viewer: 1,
    owner:  10
  }

  has_many :project_viewers, class_name: :ProjectUser, conditions: {role: ROLE[:viewer]}
  has_many :viewers, source: :user, through: :project_viewers

  has_many :project_owners, class_name: :ProjectUser, conditions: {role: ROLE[:owner]}
  has_many :owners, source: :user, through: :project_owners

end

app/models/project_user.rb
class ProjectUser < ActiveRecord::Base
  belongs_to :project
  belongs_to :user
end

app/models/task.rb
class Task < ActiveRecord::Base
  belongs_to :project
  
  validates_presence_of :name, :description, :difficulty_level

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :project_users
  has_many :projects, through: :project_users


  ROLE = {
    user: 1,
    admin: 100
  }

  def name
    "#{fname} #{lname}"
  end

  def is_owner_of?(project)
    self.includes?(project)
  end


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :authenticate_user!, except: [:index]
  before_action :set_project, only: [:show, :edit, :update, :destroy]
  # before_action :require_permission, only: [:edit, :destroy]
  
  # GET /projects
  # GET /projects.json
  def index
    @user = current_user
    @projects = Project.page(params[:page]).per(10)
  end

  # GET /projects/1
  # GET /projects/1.json
  def show
    @tasks = Task.all
    @project = Project.find(params[:id])
  end

  # GET /projects/new
  def new
    @project = Project.new
    # @project.owners << current_user
  end

  # GET /projects/1/edit
  def edit
    @project = current_user.projects.find_by(params[:id])

    unless @project.owned_by?
      redirect_to project_path
    end
  end

  # POST /projects
  # POST /projects.json
  def create
    @project = Project.new(project_params)

    if @project.save
      current_user.project_users.find_or_create_by(project: @project, role: 10)
      flash[:notice] = 'Project was successfully added.'

      redirect_to @project
    end

    # respond_to do |format|
    #   if @project.save
    #     format.html { redirect_to @project, notice: 'Project was successfully created.' }
    #     format.json { render action: 'show', status: :created, location: @project }
    #   else
    #     format.html { render action: 'new' }
    #     format.json { render json: @project.errors, status: :unprocessable_entity }
    #   end
    # end
  end

  # PATCH/PUT /projects/1
  # PATCH/PUT /projects/1.json
  def update
    respond_to do |format|
      if @project.update(project_params)
        format.html { redirect_to @project, notice: 'Project was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /projects/1
  # DELETE /projects/1.json
  def destroy
    @project.destroy
    respond_to do |format|
      format.html { redirect_to projects_url }
      format.json { head :no_content }
    end
  end

  def require_permission
    if current_user.ROLE != Project.find(params[:id]).ROLE
      redirect_to root_path
      #Or do something else here
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_project
      @project = ProjectUser.find_by(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def project_params
      params.require(:project).permit(:name)
    end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :authenticate_user!, except: [:index]
  before_action :set_task, except: [:index]

  def index

  end
  
  def show

  end

  def new
    @task = Task.new
  end

  def create
    # @project = Project.find(params[:project_id])
    @task = Task.create(task_params)
    # @task.project << @project

    if @task.save
      # @project.tasks.find_or_create_by(project: @project, role: 10)
      flash[:notice] = 'Task was successfully added.'

      redirect_to projects_path
    end    
  end


  def destroy
      @task = Task.find(params[:id])
      @task.destroy
      flash[:notice] = "Successfully destroyed task."
      @tasks = Task.all
    end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_task
      @project = ProjectUser.find_by(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def task_params
      params.require(:task).permit(:name, :description, :difficulty_level, :project_id)
    end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "ProjectManager" %></title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag "application", :media => "all" %>
  </head>
  <body>

    <div class="navbar navbar-fixed-top">
      <div class="navbar-inner">
        <div class="container">
          <a class="btn btn-navbar" data-target=".nav-collapse" data-toggle="collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </a>
          <%= link_to 'ProjectManager', root_path, class: 'brand' %>
          <div class="container nav-collapse">
            <ul class="nav">
              <li class="<%= 'active' if params[:controller] == 'projects' %>">
                <%= link_to "Projects", projects_path %>
              </li>
            </ul>

            <ul class="nav user-nav">

              <% if user_signed_in? %>
							<li role="presentation" class="dropdown">
							    <a class="dropdown-toggle" data-toggle="dropdown" href="#" role="button" aria-expanded="false">
										<%= glyph(:cog, {tag: :span}) %>
									  <span class="caret"></span>
							    </a>
							    <ul class="dropdown-menu" role="menu">
										<li><%= link_to current_user.name %></li>
										<li class="divider">
		                <li><%= link_to "My Account", edit_user_registration_path %></li>
										<li class="divider">
		                <li><%= link_to "Sign out", destroy_user_session_path, method: :delete %></li>
							    </ul>
							  </li>
              <% else %>
                <li><%= link_to "Sign in", user_session_path %></li>
                <li><%= link_to "Sign up", new_user_registration_path %></li>
              <% end %>
            </ul>


          </div><!--/.nav-collapse -->
        </div>
      </div>
    </div>

    <div class="container">
        <div class="content">
            <%= bootstrap_flash %>
            <%= yield %>
        </div><!--/content-->

      <footer>
        <p>&copy; Company 2013</p>
      </footer>

    </div> <!-- /container -->

    <!-- Javascripts
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <%= javascript_include_tag "application" %>

  </body>
</html>

app/views/pages/home.html.erb
<h1>Welcome to your new Ninefold app!</h1>

app/views/projects/_form.html.erb
<%= form_for(@project) do |f| %>
  <% if @project.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@project.errors.count, "error") %> prohibited this project from being saved:</h2>

      <ul>
      <% @project.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/projects/edit.html.erb
<h1>Editing project</h1>

<%= render 'form' %>

<%#= @project.to_yaml %>

<%= link_to 'Show', @project %> |
<%= link_to 'Back', projects_path %>

app/views/projects/index.html.erb
<h1>Listing projects</h1>

<table class="table">
  <thead>
    <tr>
      <th>Name</th>
      <th>Actions</th>
    </tr>
  </thead>

  <tbody>
    <% @projects.each do |project| %>
      <tr>
        <td><%= project.name %></td>
        <td><%#= project.owners.to_yaml %>
          <%= link_to 'Show', project, class: 'btn' %>
					<%# if project_owned_by_user(project, current_user) %>
          	<%= link_to 'Edit', edit_project_path(project), class: 'btn' %>
          	<%= link_to 'Destroy', project, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-danger' %>
					<%# end %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= paginate @projects %>


<%= link_to 'New Project', new_project_path %>

app/views/projects/new.html.erb
<h1>New project</h1>

<%= render 'form' %>

<%= link_to 'Back', projects_path %>

app/views/projects/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @project.name %>
</p>

  <ul>
  <% @tasks.each do |task| %>
    <li><%= task.name %></li>
    <td><%= link_to 'Edit', edit_task_path(task), :remote => true %></td>
    <td><%= link_to 'Destroy', task, method: :delete, data: { confirm: 'Are you sure?', remote: true } %></td>
			<%#= link_to "Ajax", link_path(link), method: :delete, id: link.id, data: { confirm: "Really?", remote: true } %>
  <% end %>
  </ul>

<%= link_to 'Add Task', new_task_path(project_id: @project.id) %> |
<%= link_to 'Edit', edit_project_path(@project) %> |
<%= link_to 'Back', projects_path %>

app/views/tasks/_form.html.erb
<%= form_for(@task) do |f| %>
  <% if @task.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@task.errors.count, "error") %> prohibited this task from being saved:</h2>

      <ul>
      <% @task.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
	
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_field :description %>
  </div>

  <div class="field">
    <%= f.label :difficulty_level %><br>
    <%= f.text_field :difficulty_level %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/tasks/destroy.js.erb
$("#<%= dom_id @entry %>").remove();

app/views/tasks/edit.html.erb
<h1>Editing task</h1>

<%= render 'form' %>

<%= link_to 'Show', @task %> |
<%= link_to 'Back', tasks_path %>

app/views/tasks/index.html.erb
<h1>Listing tasks</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th>Difficulty level</th>
      <th>Project</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @tasks.each do |task| %>
      <tr>
        <td><%= task.name %></td>
        <td><%= task.description %></td>
        <td><%= task.difficulty_level %></td>
        <td><%= task.project %></td>
        <td><%= link_to 'Show', task %></td>
        <td><%= link_to 'Edit', edit_task_path(task) %></td>
        <td><%= link_to 'Destroy', task, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Task', new_task_path %>

app/views/tasks/new.html.erb
<h1>New task</h1>

<%= render 'form' %>

<%= link_to 'Back', tasks_path %>

app/views/tasks/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @task.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @task.description %>
</p>

<p>
  <strong>Difficulty level:</strong>
  <%= @task.difficulty_level %>
</p>

<p>
  <strong>Project:</strong>
  <%= @task.project %>
</p>

<%= link_to 'Edit', edit_task_path(@task) %> |
<%= link_to 'Back', tasks_path %>